# Section 4.1 Practice Worksheet**

### **Exercise 1: Creating ndarrays (2 min)**

1. Create a 1D NumPy array containing the numbers **10, 20, 30, 40, 50**.
2. Create a 2D NumPy array with the following values:

```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

3. Check and print the **data type (`dtype`)** of the arrays you created.

In [1]:
import numpy as np
import pandas as pd
print("All libaries imported successfully")

All libaries imported successfully


In [2]:
# Type your solution here:
data = np.array([10, 20, 30, 40, 50])
two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(data, "Data type is:", data.dtype)
print(two_d_array, "Data type is:", data.dtype)

[10 20 30 40 50] Data type is: int64
[[1 2 3]
 [4 5 6]
 [7 8 9]] Data type is: int64


### **Exercise 2: Arithmetic with Arrays (3 min)**

Given the 1D array `arr = np.array([1, 2, 3, 4])`, perform the following:

1. Multiply every element by 3.
2. Add another array `np.array([10, 20, 30, 40])` to `arr`.
3. Compute the square of each element in `arr`.

In [3]:
# Type your solution here:
arr = np.array([1, 2, 3, 4])

# Multiplying each element by 3
print(arr * 3)

#Add another array 
print(arr + np.array([10, 20, 30, 40]))

#Square of each element in the array
print(arr ** 2)


[ 3  6  9 12]
[11 22 33 44]
[ 1  4  9 16]


### **Exercise 3: Basic Indexing and Slicing (3 min)**

Given the 2D array:

```python
arr2d = np.array([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])
```

1. Select the element `50`.
2. Select the **first row**.
3. Select the **last column**.
4. Select a **2x2 subarray** containing the top-left four elements.

In [4]:
# Type your solution here:
arr2d = np.array([[10, 20, 30], [40, 50, 60],[70, 80, 90]])
print(arr2d)

# Selecting the element 50
print(arr2d[1][1])

# Select the first row
print(arr2d[0])

#Select the last column
print(arr2d[2])

#Select 2*2 subarry
print(arr2d[:2, 1:])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
50
[10 20 30]
[70 80 90]
[[20 30]
 [50 60]]


### **Exercise 4: Boolean Indexing (2 min)**

Given the array `arr = np.array([5, 10, 15, 20, 25])`:

1. Create a boolean array where elements are **greater than 15**.
2. Use the boolean array to extract elements from `arr` that are greater than 15.


In [5]:
# Type your solution here:
arr1_b = np.array([5, 10, 15, 20, 25])

#Bolean array where elements are graeter than 15
greater = arr1_b > 15
print(greater)

#Bolean to extract elements from arr1_b greater than 15
print(arr1_b[greater])



[False False False  True  True]
[20 25]


### **Exercise 6: Transposing and Swapping Axes (3 min)**

Given the 2D array:

```python
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
```

1. Transpose the array.
2. Swap the two axes of `arr2d` (note: `arr2d` has shape (2, 3)).
3. Print the shape of the original and transposed arrays.


In [6]:
# Type your solution here:
arr2d2 = np.array([[1, 2, 3], [4, 5, 6]])

#Transponse Array
transpose = arr2d2.T
print(transpose)

#Swapp axes 
print(arr2d2.swapaxes(0,1))

#Printing the shape of original and transposed array
print("Original  array shape: " , arr2d2.shape)
print("Transponse  array shape: " , transpose.shape)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
Original  array shape:  (2, 3)
Transponse  array shape:  (3, 2)
